language: java
jdk:
  - oraclejdk8

before_install:
  - echo DB_HOST=$DBHOST >> src/main/resourves/.env
  - echo DB_PORT=$DBPORT >> src/main/resourves/.env
  - echo DB_DATABASE=$DBNAME >> src/main/resourves/.env
  - echo DB_USERNAME=$DBUSER >> src/main/resourves/.env
  - echo DB_PASSWORD=$DBPASS >> src/main/resourves/.env

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipiens:
      - anders@wiberg.tech
    on_success: never
    on_failure: change
