language: java
jdk:
  - oraclejdk8

before_install:
  - ls
  - find . -name sql.properties

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipiens:
      - anders@wiberg.tech
    on_success: never
    on_failure: change
