language: java
jdk:
  - oraclejdk8

before_install:
  - echo DB_HOST=$DBHOST >> .env
  - echo DB_PORT=$DBPORT >> .env
  - echo DB_DATABASE=$DBNAME >> .env
  - echo DB_USERNAME=$DBUSER >> .env
  - echo DB_PASSWORD=$DBPASS >> .env

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipiens:
      - anders@wiberg.tech
    on_success: never
    on_failure: change